Doc: Add v0.5.0 RN.
intel/edge-conductor pull request #14
Opened 2022-09-07 09:34 UTC by qianouyang

* Add v0.5.0 release notes.
Signed-off-by: qouyang <qian.ouyang@intel.com>

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Replace all uses of the term "experience kit" with "package/kit"
```suggestion
*  Replace "experience kit" terms by "package" or "kit"
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Declaratively node joining.
```suggestion
*  Support declarative node joining.
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Significantly reduce build and deployment time for EC cluster and service deployment
```suggestion
*  Reduce the time for EC cluster build and service deployment
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Upgrade latest version of supported Cluster for v0.5.0 (Need a list)
```suggestion
*  Upgrade to the latest versions on cluster  infra components:(Need a list)
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Upgrade supported services for V0.5.0 （Need a list)
```suggestion
*  Upgrade to the latest versions on supported services: (Need a list)
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Enable Debian 11.3 OS support
as the host OS for all cluster nodes?

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Enable Ubuntu 22.04 OS & preempt_RT support
```suggestion
*  Support Edge node with Ubuntu 22.04 as host OS & preempt_RT
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Add Cert-Management support
```suggestion
*  integrated "cert-Management" service from upstream
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Enable error index for the error message
```suggestion
*  Enable error code and indexing for the error messages
```

2022-09-08 05:34 UTC, yhu6 commented on RELEASE-NOTES.md
> +*  Add 3 tutorials of "Hello Cluster Helm", "Web-info" and "RKE deployment"
```suggestion
*  Add 3 user tutorial documents: "Hello Cluster Helm", "Web-info" and "RKE deployment"
```

2022-09-09 06:59 UTC, qianouyang commented on RELEASE-NOTES.md
> +*  Enable Debian 11.3 OS support
as host os.

2022-09-15 16:44 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Reduce the time for EC cluster build and service deployment
```suggestion
*  Reduce the time for Edge Conductor cluster build and service deployment
```

2022-09-15 16:44 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Upgrade to the latest versions on cluster  infra components:(Need a list)
```suggestion
*  Upgrade to the latest versions on cluster infrastructure components:(Need a list)
```

2022-09-15 16:45 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Upgrade to the latest versions on cluster  infra components:(Need a list)
Should remove "Need a list" or put a list in?

2022-09-15 16:45 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Upgrade to the latest versions on supported services: (Need a list)
Remove "Need a list" or put a list in?

2022-09-15 16:46 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Support Edge node with Ubuntu 22.04 as host OS & preempt_RT
```suggestion
*  Support edge node with Ubuntu 22.04 as host OS & preempt_RT
```

2022-09-15 16:46 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Enable error code and indexing for the error messages
```suggestion
*  Enable error code and indexing for error messages
```

2022-09-15 16:48 UTC, jnadelbx commented on RELEASE-NOTES.md
> +*  Add 3 user tutorial documents: "Hello Cluster Helm", "Web-info" and "RKE deployment"
```suggestion
*  Add 3 user tutorial documents: "Hello Cluster Helm," "Web-info," and "RKE deployment"
```

2022-09-15 16:49 UTC, jnadelbx commented on RELEASE-NOTES.md
> +Description:
Put in description.

2022-09-15 16:50 UTC, jnadelbx commented on RELEASE-NOTES.md
> +nodes, the user name and password is not set from the Package Kit
```suggestion
nodes, the user name and password is not set from the package kit
```

2022-09-15 16:51 UTC, jnadelbx commented on RELEASE-NOTES.md
> +Description: When using CAPI deploy cluster with crio as container runtime, there is error message "overlayfs: unrecognized mount option "volatile" or missing value" on the provisioned nodes. This me
```suggestion
Description: When using CAPI deploy cluster with crio as container runtime, the error message "overlayfs: unrecognized mount option "volatile" or missing value" occurs on the provisioned nodes. This message is by design of the upstream project. Refer to the [known issue](https://github.com/cri-o/cri-o/issues/4773) of CRI-O.
```

2022-09-15 16:54 UTC, jnadelbx requested changes
Doc reviewed changes requested.

2022-09-16 03:26 UTC, qianouyang commented on RELEASE-NOTES.md
> +*  Upgrade to the latest versions on cluster  infra components:(Need a list)
Removed, the List is under the feature & version table.

2022-09-16 03:26 UTC, qianouyang commented on RELEASE-NOTES.md
> +*  Upgrade to the latest versions on supported services: (Need a list)
Removed. Same as above.

2022-09-16 05:00 UTC, sunausti approved these changes

2022-09-21 00:26 UTC, jnadelbx approved these changes

2022-09-21 01:25 UTC, ychen2u approved these changes

2022-09-21 02:15 UTC, merged